#Gateway: Entry Point into the Mesh
# Purpose:Defines how and where external traffic enters your Istio service mesh.
# What it does:
    #Exposes your app outside the cluster (via LoadBalancer or Ingress).
    #Listens on specific ports (e.g., HTTP/80).
    #Binds to a specific host (e.g., myapp.example.com).

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: canary-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
