#VirtualService: Traffic Routing Logic
#Purpose:Defines how traffic is split between different versions (v1, v2) of your service.
#What it does:
     #Routes traffic to v1, v2 based on weights (e.g., 80% to v1, 20% to v2).
     #Uses rules to control traffic routing during canary rollout.
     
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: canary-app
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/canary-gateway
  http:
    - route:
        - destination:
            host: canary-app
            subset: v1
          weight: 80
        - destination:
            host: canary-app
            subset: v2
          weight: 20
